### ISSUE TITLE
Feature: Chat message or notification on zone change listing all jobs with incomplete hunt log in that zone

### ISSUE THREAD

**Issue by alydevs** [Infiziert90/Hunty#10]
Perhaps it could also show how much overlap there is. Or when a kill is recorded, a notification could indicate which jobs also need kills on that mob.

e.g if i was to zone in to South Shroud at the moment, a Dalamud notification might come up saying

Hunty: South Shroud 1/11
Gladiator 0/4
Pugilist 0/4
Thaumaturge 1/3

If it was a chat message the job names could be links that open the respective current rank/zone in the Hunty dialog. I'm not sure if Dalamud notifications can have clickable areas, they'd disappear too fast anyway.

**Comment by Infiziert90** [comment]
I can look into it

**Comment by alydevs** [comment]
Thanks! I'm also using it as motivation to get a dalamud plugin dev workspace set up and try to get it going myself

**Comment by Infiziert90** [comment]
PRs are also welcome, currently not enough time on hand to look deep into it

**Comment by alydevs** [comment]
I didn't realise there was a Companion feature, that may provide the feature I wanted to implement already. /huntyxl is cool as well. A toggle for notifications when there's unclaimed hunt log marks in a zone might still be neat tho
