### ISSUE TITLE
Smaller Minimum window size?

### ISSUE THREAD

**Issue by TheSoftest** [Infiziert90/Hunty#11]
I'm finding the default size of the /hunty window to be a bit too big to use comfortably, as it covers up too much of my screen. Looking at Hunty/Windows/MainWindow.cs, it seems like the MinimumSize of the main window is hardcoded to be 650x400px, which covers a significant portion of my screen in practice (almost a quarter). I think it would be better if there were a way to make the window a bit smaller so I could move it off to the side when it's not in use (or perhaps have an option to scale the ui so it works better on lower resolution monitors?)

**Comment by Infiziert90** [comment]
The hardcoded resolution is already scaled by dalamud, it all depends on your selected font size in the dalamud options (default is 12pt)

With a smaller screen should you just select a smaller font size there and every plugin will automatically adjust to fit that size better :)
