### ISSUE TITLE
Plugin doesn't update when changing Grand Company

### ISSUE THREAD

**Issue by foophoof** [Infiziert90/Hunty#13]
I just changed grand company, and went to start the hunting log on the new GC, but it looks like Hunty still thinks I'm in the old GC, I'm guessing because it looks like it only checks GC on login and doesn't update when the GC changes.

**Comment by foophoof** [comment]
Ah, I said that and then noticed that [it re-pulls when changing jobs](https://github.com/Infiziert90/Hunty/blob/4fddce2b9efddb08bbdaf1cf3fa8de5542940983/Hunty/Hunty.cs#L165), so just switching jobs updated the plugin.

This can maybe be closed, I guess?

**Comment by Infiziert90** [comment]
Yeah, switching GC is auch a rarity that it just not worth checking everytime

It does on job switch, and that is good enogu really
