### ISSUE TITLE
Hunty XL Maelstrom issue

### ISSUE THREAD

**Issue by FunkeyMonkey** [Infiziert90/Hunty#8]
My Huntyxl is not showing Maelstrom hunts for some reason. It shows them in the small book but not XL. The message i get it This job is done with the hunting log, which is correct i've completed it on Arcanist but still have rank 3 for Maelstrom to finish.

**Comment by Infiziert90** [comment]
XL is meant for multiple jobs, not for GC
That's why it doesn't implement it

**Comment by FunkeyMonkey** [comment]
Ah my bad, i saw the Maelstrom at the top and thought it worked for GC too. Thanks for quick reply!
