### ISSUE TITLE
Add support for CN client?

### ISSUE THREAD

**Issue by AtmoOmen** [Infiziert90/Hunty#9]
Since there are no other language resources in CN client, Hunty will throw exceptions when trying to install on the CN client.

To solve that, I made a monsters_cn.json file. [monsters_cn.json](https://github.com/Infiziert90/Hunty/files/13487866/monsters_cn.json)

Also because there's no ChineseSimplifed in global dalamud's ClientLanguage enum, maybe it's not easy to solve this problem from upstream.

Whatever, if you think this is acceptable and you can solve, just take the file. If not, still thanks for your work for making this excellent plugin!

Maybe for reference, this is how I adapt Hunty into CN dalamud: https://github.com/Infiziert90/Hunty/commit/a7749d2fd8f0b3e0419d9ddf4b9cf49ee6c892b8

**Comment by Infiziert90** [comment]
I can look into it later
